#!/bin/bash -e
# Bundle the files used by pdflatex into a single file 

r=${1%.tex}
if [[ ! -e $r.tex ]]; then
  echo "File \"$r.tex\" does not exist - quitting!"
  echo "Usage: $0 <texfile>"
  exit -1
fi

# pdflatex the document and extract the file list from the log file
latexmk -pdf "$r"
fl=`mawk 'BEGIN {record=0;}
   /^ *\*File List\* *$/ {record=1;}
   / *\*\*\*+ *$/ {record=0;}
   { if (record && record++ >= 2) { print $1; } }' $r.log | sort | uniq`

echo "File List is $fl"
echo "END FILE LIST"

# take only files in the current directory
for f in $fl; do
  if [[ -e ./$f ]];  then
    fp="$fp $f"
  fi
done

if [[ -e $r.bib ]]; then
  echo "Leaving out BibTeX file $r.bib - arXiv doesn't want it"
fi
fp="$r.tex $fp"

fp="$r.pdf $fp"

echo "!!!!NOTE: Your latex file must include the \listfiles command!!!!"
# make an archive of everything
echo "Creating TGZ archive..."
tar czvf "$r.tgz" $fp |  sed 's/^ */  /' 
echo "Creating ZIP archive..."
zip "$r.zip" $fp | sed 's/^ */  /' 
