#!/bin/bash -e
# Bundle the files used by pdflatex into a single file 

r=${1%.tex}
if [[ ! -e $r.tex ]]; then
  echo "File \"$r.tex\" does not exist - quitting!"
  echo "Usage: $0 <texfile>"
  exit -1
fi

# pdflatex the document and extract the file list from the log file
pdflatex $r
fl=`awk --posix 'BEGIN {record=0;}
   /^[[:space:]]*\*File List\*[[:space:]]*$/ {record=1;}
   /^[[:space:]]*\*{3,}[[:space:]]*$/ {record=0;}
   { if (record && record++ >= 2) { print $1; } }' $r.log | sort | uniq`

# take only files in the current directory
for f in $fl; do
  if [[ -e ./$f ]];  then
    fp="$fp $f"
  fi
done

if [[ -e $r.bib ]]; then
  echo "Leaving out BibTeX file $r.bib - arXiv doesn't want it"
fi
fp="$r.tex $fp"

echo "!!!!NOTE: Your latex file must include the \listfiles command!!!!"
# make an archive of everything
echo "Creating archive..."
tar czvf $r.tgz $fp
echo "done"
echo "!!!!NOTE: Your latex file must included the \listfiles command!!!!"
echo "Created file $r.dvi - check the pdflatex output for errors"
