#!/bin/bash
# Bundle the files used by pdflatex into a single file to submit to
# the arxiv


r=$1
if [[ ! -e $r.tex ]]; then
  echo "File $r.tex does not exist - quitting!"
  exit -1
fi

# latex the document and extract the file list from the log file
pdflatex $r
fl=`awk 'BEGIN {record=0;}
   /\*File List\*/ {record=1;}
   /\*\*\*\*\*\*/ {record=0;}
   { if (record && record++ >= 2) { print $1; } }' $r.log`

# take only files in the current directory
for f in $fl; do
  if [[ -e ./$f ]];  then
    fp="$fp $f"
  fi
done
fp="$r.tex $fp"

# make an archive of everything
echo "Creating archive..."
tar czvf $r.tgz $fp | awk '{print "  " $1}'
echo "done"
