#!/bin/bash -e

## This should be your dropbox user id
## Get it by using the 'get public url' feature in dropbox
uid=2333481
dir="${1%/}"
cd ~/Dropbox/Public/$dir

urlhead="http://dl.dropbox.com/u/$uid"
if [ -n $dir ]; then
  urlhead="$urlhead/$dir"
fi

header=`cat <<END
<html>
  <head>
    <title>Public Dropbox - Pat Morin</title>
  </head>
  <body>
    <h1>Public Dropbox $dir</h1>
    <ul>
END
`

for f in *; do
   if [ -z $dir ]; then echo $"  $f" ; else echo "  $dir/$f" ; fi
   if [[ -f $f ]]; then
     index="$index      <li><a href='$urlhead/$f'>$f</a></li>\n"
   elif [[ -d $f ]]; then
     index="$index      <li><a href='$urlhead/$f/index.html'>$f</a> (directory)</li>\n"
     if [ -z $dir ]; then
        "$0" "$f"   #recurse
     else
        "$0" "$dir/$f"   #recurse
     fi
   fi 
done

footer=`cat <<'END'
    </ul>
  </body>
</html>
END
`

echo -e "$header\n$index\n$footer" > index.html

