#!/bin/bash
# Converts the picture elements in ipe file to pdf files
# Usage : ipe2pdf [<file1> <file2> ...]

if [ "$1" == '' ] ; then
    files=*.ipe
else
    files=$1
fi

for f in $files ; do
    if [[ ! -e $f  ]] ; then
	echo "Can't find file $f"
	exit -1
    fi
done

for f in $files ; do
    r=${f%.ipe}
    if [[ ( ! -e $r.pdf ) || ( $r.ipe -nt $r.pdf ) ]] ; then
	echo "$r.ipe => $r.pdf"
	epstopdf $r.ipe "--outfile=${r}.pdf"
    fi
    if [[ ( ! -e $r.eps ) || ( $r.ipe -nt $r.eps ) ]] ; then
	echo "$r.ipe => $r.eps"
	cp $r.ipe $r.eps
    fi
done

