#!/bin/bash


echo pdfovl - overlays two pdf files
if [[ $# -ne 3 ]]; then
  echo "Usage: pdfovl <infile1.pdf> <infile2.pdf> <outfile.pdf>"
  exit -1
fi
DIR=${0%/pdfovl}
echo $DIR
java -classpath $DIR:$DIR/iText-2.1.5.jar PDFOverlay "$1" "$2" "$3"
 
