#!/bin/bash


#echo $#
if [[ $# != 3 ]] ; then
    echo "Usage $0 : <filebase> <tag> <dir>"
    exit -1
fi

base=$1
tag=$2
dir=$3

latex $base
latex $base
dvips -t letter -o $base.ps $base
gzip $base.ps
pdflatex $base
pdflatex $base

if [[ $tag == '' ]] ; then
    r=$base
else
    r=$base-$tag
fi

mv $base.ps.gz $r.ps.gz
mv $base.pdf $r.pdf
scp $r.pdf $r.ps.gz morin@cg.scs.carleton.ca:public_html/publications/$dir/
