#!/bin/bash

# unique identifier to append onto directory name
u="uniq548dsjs67-`date +%s`"

function rotate() {
  local dstdir="$1"
  local nv="7"
  
  local i="$nv"
  rm -rf "$dstdir.$i"
  local prev="$i"
  while [[ $((i--)) -gt 0 ]]; do
    mv "$dstdir.$i" "$dstdir.$prev"
    prev="$i"
  done
}

if [[ $# -ne 2 ]]; then
  echo "Usage $0 <srcdir> <dstdir>"
  exit 1
fi

srcdir="${1%/}"
dstdir="${2%/}"

echo "Backing up $srcdir onto $dstdir"
if [[ -e "$dstdir.$u" ]]; then
  echo "WARNING: - intermediate directory alread exists - updating it"
fi
rsync -a --delete --link-dest="$dstdir.0" "$srcdir/" "$dstdir.$u"
rotate $dstdir
mv "$dstdir.$u" "$dstdir.0"

