#!/bin/bash -ex

date=`date +%F:%R`
rawfile="$date-raw.txt"
nicefile="$date.txt"
script -a -c python "$rawfile" 
cat $rawfile | perl -pe 's/\e([^\[\]]|\[.*?[a-zA-Z]|\].*?\a)//g' | col -b > $nicefile
#rm -f $rawfile
